name: CI Runner

on:
    workflow_dispatch:
        inputs:
            model_nickname: 
                description: 'Nickname of the model - to be used to access the model data on S3'
                required: true
                type: string
            model_zip_url:
                description: 'Presigned url for the model zip-file'
                required: true
                type: true


jobs:
    test-model:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        env: 
            S3_HOST: ${{secrets.S3_HOST}}
            S3_BUCKET: ${{secrets.S3_BUCKET}}
            S3_ROOT_FOLDER: ${{secrets.S3_ROOT_FOLDER}}
            S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
            S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
        steps:
            - uses: actions/checkout@v3

            - name: Install workflow script dependencies
              run: |
                    echo "Installing workflow script dependencies"
                    python -m pip install --upgrade pip
                    python -m pip install "minio==7.2.0"
            - name: Unzip model file
              run: |
                    python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Unzipping model-file of ${{inputs.model_nickname}}" "1" "8"  
                    python .github/scripts/unzip_model.py "${{inputs.model_nickname}}" "{{inputs.model_zip_url}}" 
            - name: Install dependencies
              run: |
                    python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Installing dependencies of ${{inputs.model_nickname}}" "2" "8"  
                    echo "Installing dependencies"
                    python -m pip install --upgrade pip
                    python -m pip install flake8 pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Additional Steps
              run: |
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Running additional steps of ${{inputs.model_nickname}}" "3" "8"  
                  echo "Running additional steps..."
                  sleep 30
                  echo "Done"
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Done running additional steps of ${{inputs.model_nickname}}" "4" "8"  

            - name: Main testing
              run: |
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Running main testing of ${{inputs.model_nickname}}" "5" "8"  
                  echo "Running main testing"
                  sleep 30
                  echo "Done"
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Testing complete of ${{inputs.model_nickname}}" "6" "8"  

            - name: Publish within S3
              run: |
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Running publishing of ${{inputs.model_nickname}}" "7" "8"  
                  echo "Somehow doing publising workflow 🤔"
                  sleep 30
                  echo "Done"
                  python .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Publishing complete of ${{inputs.model_nickname}}" "8" "8"  
