name: CI Runner

on:
    workflow_dispatch:
        inputs:
            status_url:
                description: 'URL endpoint for status to be posted to'
                required: false
                type: string
            model_nickname: 
                description: 'Nickname of the model - to be used to access the model data on S3'
                required: true
                type: string

jobs:
    test-model:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        env: 
            S3_HOST: ${{secrets.S3_HOST}}
            S3_BUCKET: ${{secrets.S3_BUCKET}}
            S3_ROOT_FOLDER: ${{secrets.S3_ROOT_FOLDER}}
            S3_ACCESS_KEY_ID: ${{secrets.S3_ACCESS_KEY_ID}}
            S3_SECRET_ACCESS_KEY: ${{secrets.S3_SECRET_ACCESS_KEY}}
        steps:
            - uses: actions/checkout@v3

            - name: Install workflow script dependencies
              run: |
                    echo "Installing workflow script dependencies"
                    python -m pip install --upgrade pip
                    python -m pip install "minio==7.2.0"
            - name: Update status
              run: sh .github/scripts/update_status.py  "${{ inputs.model_nickname }}" "Starting testing of ${{inputs.model_nickname}}"  
            
            - name: Install dependencies
              run: |
                    sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Installing dependencies of ${{inputs.model_nickname}}"  
                    echo "Installing dependencies"
                    python -m pip install --upgrade pip
                    python -m pip install flake8 pytest
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Additional Steps
              run: |
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Running additional steps of ${{inputs.model_nickname}}"  
                  echo "Running additional steps..."
                  sleep 30
                  echo "Done"
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Done running additional steps of ${{inputs.model_nickname}}"  

            - name: Main testing
              run: |
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Running main testing of ${{inputs.model_nickname}}"  
                  echo "Running main testing"
                  sleep 30
                  echo "Done"
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Testing complete of ${{inputs.model_nickname}}"  

            - name: Publish within S3
              run: |
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Running publishing of ${{inputs.model_nickname}}"  
                  echo "Somehow doing publising workflow 🤔"
                  sleep 30
                  echo "Done"
                  sh .github/scripts/update_status.sh  "${{ inputs.model_nickname }}" "Publishing complete of ${{inputs.model_nickname}}"  
