name: CI Runner

on:
    workflow_dispatch:


jobs:
    test-model:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.9", "3.10", "3.11"]

    steps:
        - name: Checkout latest code 
          uses: actions/checkout@v3
        
        - name: Notify CI workflow started
          run: |
              echo `which python` 

        
        - name: Install Python
          uses: actions/setup-python@v3      
          with:
                python-version: ${{ matrix.python-version }} 

        - name: Install dependencies
          run: |
                echo "Installing dependencies"
                python -m pip install --upgrade pip
                python -m pip install flake8 pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Additional Steps
          run: |
              echo "Running additional steps..."
              sleep 2
              echo "Done"

        - name: Main testing
          run: |
              echo "Running main testing"
              sleep 30
              echo "Done"


